name: CI checks

on:
  pull_request:
    branches: [ master ]
    

jobs:
  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: client-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: client-yarn-
    - run: yarn
    - run: yarn lint
    - run: yarn build
    - run: yarn test
