name: CI checks

on:
  pull_request:
    branches: [ master ]
    

jobs:
  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/client
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: yarn
    - run: yarn build
    - run: yarn test
      env:
        CI: true